use anyhow::{Context, anyhow, bail, ensure};
use markdown::{
    ParseOptions,
    mdast::{FootnoteDefinition, Node},
};
use notify::{EventKind, RecursiveMode, Watcher, event::ModifyKind};
use std::{
    borrow::Cow,
    cmp::Ordering,
    collections::{BTreeMap, HashMap, HashSet},
    fs::{self},
    hash::{DefaultHasher, Hash, Hasher},
    io::{self, BufWriter, Read},
    net::{SocketAddr, TcpListener, TcpStream},
    path::{Path, PathBuf},
    process::{Command, ExitCode},
    sync::{Arc, Condvar, Mutex},
    thread::{self},
    time::{Duration, Instant},
};

use std::io::Write;

const AUTOGENERATED_COMMENT: &str = "<!--\nThis file has been auto-generated by main.rs from a markdown file of the same name.\nDo not edit it by hand.\n-->";
const BACK_LINK: &str = r#"<p><a href="/blog"> ⏴ Back to all articles</a></p>"#;
const BASE_URL: &str = "https://gaultier.github.io/blog";
const FEED_UUID: [u8; 16] = [
    0x9c, 0x06, 0x5c, 0x53, 0x31, 0xbc, 0x40, 0x49, 0xa7, 0x95, 0x93, 0x68, 0x02, 0xa6, 0xb1, 0xdf,
];

const STANDARD_LANGS: [&str; 21] = [
    "c",
    "css",
    "cmake",
    "cpp",
    "diff",
    "dockerfile",
    "go",
    "html",
    "javascript",
    "json",
    "kotlin",
    "lua",
    "makefile",
    "markdown",
    "plaintext",
    "rust",
    "scheme",
    "shell",
    "sql",
    "x86asm",
    "yaml",
];

const CUSTOM_LANGS: [&str; 5] = ["awk", "dtrace", "gnuplot", "odin", "toml"];
// Upper bound on the size of an incoming HTTP request, to bound the memory a
// single connection can make us allocate.
const HTTP_REQUEST_SIZE_MAX: usize = 1024 * 1024; // 1 MiB.
const HTTP_READ_TIMEOUT: Duration = Duration::from_secs(30);
const IGNORED_MARKDOWN_FILES: [&str; 3] = ["README.md", "todo.md", "index.md"];

struct Title {
    text: String,
    depth: u8,
    start_md_offset: usize,
    slug: String,
}

#[derive(Clone, Hash)]
struct GitStat {
    creation_date: String,
    modification_date: String,
    path_from_git_root: String,
}

#[derive(Clone)]
struct Article {
    git_stat: GitStat,
    html_title: String,
    // The same title, as plain text, for non-HTML contexts.
    text_title: String,
    html_path: PathBuf,
    tags: Vec<String>,
    html_output: Vec<u8>,
}

// Match on the file name, not on the path: the generator and the watcher used
// to disagree about what "ignored" meant, so a file in a subdirectory was an
// article to one of them and noise to the other.
fn is_ignored_markdown_file(path: &Path) -> bool {
    path.file_name().is_some_and(|name| {
        IGNORED_MARKDOWN_FILES
            .iter()
            .any(|ignored| name == AsRef::<Path>::as_ref(ignored))
    })
}

fn hash_article_inputs(
    git_stat: &GitStat,
    html_header: &[u8],
    html_footer: &[u8],
    md_content: &[u8],
) -> u64 {
    let mut hasher = DefaultHasher::new();
    // The rendered article embeds the path and both dates, so they belong in
    // the key: two articles with the same body are not interchangeable.
    git_stat.hash(&mut hasher);
    html_header.hash(&mut hasher);
    html_footer.hash(&mut hasher);
    md_content.hash(&mut hasher);
    hasher.finish()
}

// Lint an article body. The `<h1>` is rendered from the `Title:` metadata, so
// the body starts one level below it: the first heading must be `##`, and each
// heading may go at most one level deeper than the previous one.
fn md_lint(node: &Node, md_path: &Path) -> anyhow::Result<()> {
    let mut previous_heading_depth = 1u8;
    md_lint_rec(node, md_path, &mut previous_heading_depth)
}

fn md_lint_rec(node: &Node, md_path: &Path, previous_heading_depth: &mut u8) -> anyhow::Result<()> {
    match node {
        Node::Root(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::Blockquote(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::FootnoteDefinition(_) | Node::MdxJsxFlowElement(_) => Ok(()),
        Node::List(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::InlineMath(_)
        | Node::MdxjsEsm(_)
        | Node::Toml(_)
        | Node::Yaml(_)
        | Node::Break(_)
        | Node::InlineCode(_) => Ok(()),
        Node::Delete(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::Emphasis(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::MdxTextExpression(_)
        | Node::FootnoteReference(_)
        | Node::Html(_)
        | Node::Image(_)
        | Node::ImageReference(_)
        | Node::MdxJsxTextElement(_) => Ok(()),

        Node::Link(link) => {
            // TODO: external links.
            if !link.url.starts_with("/") {
                return Ok(());
            }

            if !link.url.starts_with("/blog/") {
                bail!("wrong internal link, must start with '/blog': {}", link.url);
            }
            if link.url.ends_with(".md") {
                bail!("wrong internal link, must not end with '.md': {}", link.url);
            }

            if link.url.contains("gaultier.github.io") {
                bail!("wrong internal link, points to public blog: {}", link.url);
            }
            Ok(())
        }
        Node::LinkReference(_) => Ok(()),
        Node::Strong(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::Text(text) => {
            // Spellings that are always wrong: `DTrace`, `KiB` and `kB` have
            // one correct casing each.
            let incorrect = ["dtrace", "dTrace", "Dtrace", "Kib", "kb", "KB", "Kb"];
            // Splitting on non-letters yields maximal runs of letters, which is
            // exactly the notion of "word" this lint wants: `workbench` is one
            // word and never matches `kb`, while the `KB` in `100KB` and the
            // `dtrace` in `dtrace-based` are words of their own. Note that
            // `split_whitespace` would not do: it keeps the digits and the
            // punctuation attached.
            for word in text.value.split(|c: char| !c.is_alphabetic()) {
                if incorrect.contains(&word) {
                    bail!(
                        "incorrect spelling `{}`: file={:?} position={:?}",
                        word,
                        md_path.to_str(),
                        text.position
                    );
                }
            }

            Ok(())
        }

        Node::Code(code) => {
            match &code.lang {
                None => {
                    bail!(
                        "missing language for code block: file={:?} position={:?}",
                        md_path.to_str(),
                        code.position
                    );
                }
                Some(lang) => {
                    if !(STANDARD_LANGS.contains(&lang.as_str())
                        || CUSTOM_LANGS.contains(&lang.as_str()))
                    {
                        bail!("unknown lang: {} position={:?}", lang, code.position);
                    }
                }
            }
            Ok(())
        }
        Node::Math(_) | Node::MdxFlowExpression(_) => Ok(()),
        Node::Heading(x) => {
            if x.depth < 2 {
                bail!(
                    "heading must be `##` or deeper, the `#` is rendered from the `Title:` metadata: file={:?} position={:?}",
                    md_path.to_str(),
                    x.position
                );
            }
            if x.depth > *previous_heading_depth + 1 {
                bail!(
                    "heading jumps from depth {} to {}, it may only go one level deeper at a time: file={:?} position={:?}",
                    previous_heading_depth,
                    x.depth,
                    md_path.to_str(),
                    x.position
                );
            }
            *previous_heading_depth = x.depth;

            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::Table(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::ThematicBreak(_) => Ok(()),
        Node::TableRow(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::TableCell(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::ListItem(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
        Node::Definition(_) => Ok(()),
        Node::Paragraph(x) => {
            for child in &x.children {
                md_lint_rec(child, md_path, previous_heading_depth)?;
            }
            Ok(())
        }
    }
}

fn git_get_articles_stats() -> anyhow::Result<Vec<GitStat>> {
    let start = Instant::now();

    let output = Command::new("git")
        .args([
            "log",
            "--format='%aI'",
            "--no-merges",
            "--diff-filter=AMRD",
            "--name-status",
            "--reverse",
            "*.md",
        ])
        .output()
        .context("failed to get git stats")?;
    ensure!(
        output.status.success(),
        "git log failed: status={} stderr={}",
        output.status,
        String::from_utf8_lossy(&output.stderr)
    );
    // git writes warnings here without failing, which is not our problem to
    // turn into a build error.
    if !output.stderr.is_empty() {
        eprintln!(
            "git log stderr: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    // Sample git output:
    // 2024-10-31T16:09:02+01:00
    //
    // M       lessons_learned_from_a_successful_rust_rewrite.md
    // A       tip_of_day_3.md
    // 2025-02-18T08:07:55+01:00
    //
    // R100    sha.md  making_my_debug_build_run_100_times_faster.md

    let res = git_parse_log(&String::from_utf8_lossy(&output.stdout))?;

    println!(
        "🗄️ git stats: {} files in {} ms",
        res.len(),
        Instant::now().duration_since(start).as_millis()
    );

    Ok(res)
}

fn git_parse_log(output_str: &str) -> anyhow::Result<Vec<GitStat>> {
    let mut lines = output_str.lines().peekable();

    let mut res: BTreeMap<String, GitStat> = BTreeMap::new();

    loop {
        // End?
        let line = match lines.next() {
            None => {
                break;
            }
            Some(line) => line,
        };

        let date_trimmed = line.trim_matches('\'');
        ensure!(
            !date_trimmed.is_empty(),
            "empty date line in git log entry: `{}`",
            line
        );

        let empty = lines
            .next()
            .ok_or(anyhow!("expected empty line in git log entry, after date"))?;
        ensure!(
            empty.is_empty(),
            "expected an empty line after the date in git log entry, got: `{}`",
            empty
        );

        // Files.
        loop {
            // End?
            let line = match lines.peek() {
                None => {
                    break;
                }
                Some(line) if line.is_empty() || line.starts_with("'20") => break,
                Some(_) => lines.next().unwrap(), // Safe due to `peek()`.
            };

            let mut split = line.splitn(3, '\t');
            match (split.next(), split.next(), split.next()) {
                (Some("D"), Some(path), None) => {
                    ensure!(!path.is_empty(), "empty path in git log entry: `{}`", line);
                    res.remove(path).ok_or(anyhow!(
                        "expected path in delete action in git log to already be known: {}",
                        path
                    ))?;
                }
                (Some("A"), Some(path), None) => {
                    ensure!(!path.is_empty(), "empty path in git log entry: `{}`", line);
                    let git_stat = GitStat {
                        creation_date: date_trimmed.to_owned(),
                        modification_date: date_trimmed.to_owned(),
                        path_from_git_root: path.to_owned(),
                    };
                    res.insert(path.to_owned(), git_stat);
                }
                (Some("M"), Some(path), None) => {
                    let entry = res.get_mut(path).ok_or(anyhow!(
                        "expected path in modified action in git log to already be known: {}",
                        path
                    ))?;
                    ensure!(
                        entry.modification_date.as_str().cmp(date_trimmed) != Ordering::Greater,
                        "git log is not in chronological order: path={} previous={} current={}",
                        path,
                        entry.modification_date,
                        date_trimmed
                    );
                    // Update the modification date.
                    entry.modification_date = date_trimmed.to_owned();
                }
                (Some(action), Some(path_old), Some(path_new)) if action.starts_with("R") => {
                    ensure!(
                        !path_old.is_empty() && !path_new.is_empty(),
                        "empty path in git log rename entry: `{}`",
                        line
                    );

                    // Renaming a file does not publish a new article: keep the
                    // date it was first added under its old name.
                    let old = res.remove(path_old);
                    let git_stat = GitStat {
                        creation_date: old
                            .map(|old| old.creation_date)
                            .unwrap_or_else(|| date_trimmed.to_owned()),
                        modification_date: date_trimmed.to_owned(),
                        path_from_git_root: path_new.to_owned(),
                    };
                    res.insert(path_new.to_owned(), git_stat);
                }
                _ => {
                    bail!("invalid combination in git log entry: `{}`", line);
                }
            }
        }
    }

    Ok(res.into_values().collect())
}

// TODO: Return Rc<String> or Cow<str>?
fn md_collect_titles(
    node: &Node,
    title_to_counter: &mut BTreeMap<String, u32>,
    titles: &mut Vec<Title>,
) -> anyhow::Result<()> {
    match node {
        Node::Root(root) => {
            for child in &root.children {
                md_collect_titles(child, title_to_counter, titles)?;
            }
        }
        Node::Heading(heading) => {
            let depth = heading.depth;
            // A heading is not necessarily one text node: it can hold inline
            // code, a link, or emphasis. Flatten it to plain text for the slug
            // and the table of contents.
            let mut content = String::new();
            for child in &heading.children {
                md_to_text_rec(child, &mut content);
            }
            if content.is_empty() {
                bail!(
                    "heading has no text content: position={:?}",
                    heading.position
                );
            }

            // Key the counter on the slug rather than on the title text:
            // `## Foo!` and `## Foo?` are different titles that collapse to the
            // same slug, and would otherwise both claim `id="foo"`.
            let slug = html_slug(&content);
            let counter = *title_to_counter
                .entry(slug.clone())
                .and_modify(|c| *c += 1)
                .or_insert(0);
            let slug = if counter > 0 {
                format!("{}-{}", slug, counter)
            } else {
                slug
            };
            titles.push(Title {
                text: content,
                depth,
                start_md_offset: heading
                    .position
                    .as_ref()
                    .ok_or(anyhow!("heading has no position"))?
                    .start
                    .offset,
                slug,
            });
        }
        Node::Paragraph(paragraph) => {
            for child in &paragraph.children {
                md_collect_titles(child, title_to_counter, titles)?;
            }
        }
        _ => {}
    }
    Ok(())
}

fn md_parse_metadata(md_content: &str) -> anyhow::Result<(&str, Vec<&str>)> {
    let title_line = md_content
        .lines()
        .next()
        .ok_or(anyhow!("missing title line in article metadata"))?;
    let title = title_line
        .strip_prefix("Title: ")
        .ok_or(anyhow!(
            "missing `Title: ` in title line in article metadata"
        ))?
        .trim_ascii();

    let tags_line = md_content
        .lines()
        .nth(1)
        .ok_or(anyhow!("missing tags line in article metadata"))?;
    let tags_str = tags_line
        .strip_prefix("Tags: ")
        .ok_or(anyhow!("missing `Tags: ` in tags line in article metadata"))?;
    let tags: Vec<&str> = tags_str.split(", ").map(|s| s.trim_ascii()).collect();

    Ok((title, tags))
}

// Return everything after the `---` line that closes the metadata header.
//
// The delimiter is a line of its own, right after the `Title:` and `Tags:`
// lines. Looking for the first `---` anywhere in the document would also match
// one inside the title, or a thematic break in an article whose header is
// malformed, and silently truncate everything before it.
fn md_strip_metadata(md_content: &str) -> Option<&str> {
    let mut offset = 0usize;
    for (i, line) in md_content.split_inclusive('\n').enumerate() {
        if i >= 2 && line.trim_ascii() == "---" {
            return Some(&md_content[offset + line.len()..]);
        }
        offset += line.len();
    }

    None
}

fn html_slug(s: &str) -> String {
    let mut res = String::with_capacity(s.len());

    for c in s.chars() {
        match c {
            '+' => res.push_str("plus"),
            '#' => res.push_str("sharp"),
            c if c.is_ascii_alphanumeric() => res.push(c.to_ascii_lowercase()),
            // Other runes are mapped to `-`, but we avoid consecutive `-`.
            _ if !res.ends_with('-') => {
                res.push('-');
            }
            _ => {}
        };
    }
    res.trim_matches(|c| c == '-').to_owned()
}

fn md_to_html(md_content: &str) -> anyhow::Result<Vec<u8>> {
    let mut sb = Vec::with_capacity(md_content.len());
    let md_ast = markdown::to_mdast(
        md_content,
        &ParseOptions {
            constructs: markdown::Constructs {
                gfm_autolink_literal: false,
                ..markdown::Constructs::gfm()
            },
            gfm_strikethrough_single_tilde: true,
            ..Default::default()
        },
    )
    .map_err(|err| anyhow!("failed to parse markdown: {:?}", err))?;

    let mut footnote_defs = Vec::new();

    if let Node::Root(r) = &md_ast
        && r.children.len() == 1
        && let Node::Paragraph(p) = &r.children[0]
    {
        for c in &p.children {
            md_to_html_rec(&mut sb, &mut footnote_defs, c, &[], false)?;
        }
        return Ok(sb);
    }
    md_to_html_rec(&mut sb, &mut footnote_defs, &md_ast, &[], false)?;

    Ok(sb)
}

fn md_to_text_rec(node: &Node, out: &mut String) {
    match node {
        Node::Text(text) => out.push_str(&text.value),
        // Keep the strikethrough markers: the title
        // `Making my static blog generator ~11~ 33 times faster` turns into
        // the meaningless `... 11 33 times faster` without them.
        Node::Delete(delete) => {
            out.push('~');
            for child in &delete.children {
                md_to_text_rec(child, out);
            }
            out.push('~');
        }

        Node::InlineCode(code) => out.push_str(&code.value),
        Node::Code(code) => out.push_str(&code.value),
        other => {
            if let Some(children) = other.children() {
                for child in children {
                    md_to_text_rec(child, out);
                }
            }
        }
    }
}

// Render markdown to plain text, for the places where markup is not allowed:
// `<title>`, or an Atom feed entry title.
fn md_to_text(md_content: &str) -> anyhow::Result<String> {
    let md_ast = markdown::to_mdast(
        md_content,
        &ParseOptions {
            constructs: markdown::Constructs {
                gfm_autolink_literal: false,
                ..markdown::Constructs::gfm()
            },
            gfm_strikethrough_single_tilde: true,
            ..Default::default()
        },
    )
    .map_err(|err| anyhow!("failed to parse markdown: {:?}", err))?;

    let mut res = String::with_capacity(md_content.len());
    md_to_text_rec(&md_ast, &mut res);

    Ok(res)
}

fn md_html_append(md_content: &str, html_content: &mut Vec<u8>) -> anyhow::Result<()> {
    let mut footnote_defs = Vec::new();

    let md_ast = markdown::to_mdast(
        md_content,
        &ParseOptions {
            constructs: markdown::Constructs {
                gfm_autolink_literal: false,
                ..markdown::Constructs::gfm()
            },
            gfm_strikethrough_single_tilde: true,
            ..Default::default()
        },
    )
    .map_err(|err| anyhow!("failed to parse markdown: {:?}", err))?;

    let mut md_titles = Vec::with_capacity(12);
    let mut title_to_counter: BTreeMap<String, u32> = BTreeMap::new();
    md_collect_titles(&md_ast, &mut title_to_counter, &mut md_titles)?;

    md_to_html_rec(html_content, &mut footnote_defs, &md_ast, &md_titles, false)?;
    md_render_footnote_definitions(html_content, &footnote_defs)?;

    Ok(())
}

fn capitalize_first(s: &str) -> Cow<'_, str> {
    if s.is_empty() {
        return Cow::Borrowed(s);
    }

    let mut chars = s.chars();
    let c = chars.next().unwrap(); // Safe due to `is_empty()` check.
    if c.is_uppercase() {
        Cow::Borrowed(s)
    } else {
        Cow::Owned(c.to_uppercase().collect::<String>() + chars.as_str())
    }
}

fn md_to_html_rec(
    content: &mut Vec<u8>,
    footnote_defs: &mut Vec<FootnoteDefinition>,
    node: &Node,
    titles: &[Title],
    inside_thead: bool,
) -> anyhow::Result<()> {
    match node {
        Node::Root(root) => {
            for child in &root.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
        }
        Node::Blockquote(blockquote) => {
            writeln!(content, "<blockquote>")?;

            for child in &blockquote.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            writeln!(content, "</blockquote>")?;
        }
        Node::FootnoteDefinition(footnote_definition) => {
            footnote_defs.push(footnote_definition.clone());
        }
        Node::MdxJsxFlowElement(_) => bail!(
            "unsupported markdown node: MdxJsxFlowElement position={:?}",
            node.position()
        ),
        Node::List(list) => {
            let tag = if list.ordered { "ol" } else { "ul" };
            if let Some(start) = list.start
                && start > 1
            {
                writeln!(content, r#"<{} start="{}">"#, tag, start)?;
            } else {
                writeln!(content, r#"<{}>"#, tag)?;
            }
            for child in &list.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            writeln!(content, "</{}>", tag)?;
        }
        Node::MdxjsEsm(_) => bail!(
            "unsupported markdown node: MdxjsEsm position={:?}",
            node.position()
        ),
        Node::Toml(_) => bail!(
            "unsupported markdown node: Toml position={:?}",
            node.position()
        ),
        Node::Yaml(_) => bail!(
            "unsupported markdown node: Yaml position={:?}",
            node.position()
        ),
        Node::Break(_) => bail!(
            "unsupported markdown node: Break position={:?}",
            node.position()
        ),
        Node::InlineCode(inline_code) => {
            let sanitized = text_sanitize_for_html(&inline_code.value, false);
            write!(content, "<code>{}</code>", sanitized)?;
        }
        Node::InlineMath(_) => bail!(
            "unsupported markdown node: InlineMath position={:?}",
            node.position()
        ),
        Node::Delete(delete) => {
            write!(content, "<del>")?;
            for child in &delete.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            write!(content, "</del>")?;
        }
        Node::Emphasis(emphasis) => {
            write!(content, "<em>")?;
            for child in &emphasis.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            write!(content, "</em>")?;
        }
        Node::MdxTextExpression(_) => bail!(
            "unsupported markdown node: MdxTextExpression position={:?}",
            node.position()
        ),
        Node::FootnoteReference(footnote_reference) => {
            writeln!(
                content,
                r##"<sup class="footnote-ref"><a href="#fn-{}" id="fnref-{}" data-footnote-ref>{}</a></sup>"##,
                &footnote_reference.identifier,
                footnote_reference.identifier,
                footnote_reference
                    .label
                    .as_ref()
                    .ok_or(anyhow!("footnote reference has no label"))?,
            )?;
        }
        Node::Html(html) => {
            writeln!(content, "{}", html.value)?;
        }
        Node::Image(image) => {
            write!(
                content,
                r#"<img src="{}" alt="{}" />"#,
                text_sanitize_for_html(&image.url, false),
                text_sanitize_for_html(&image.alt, false),
            )?;
        }

        Node::ImageReference(_) => bail!(
            "unsupported markdown node: ImageReference position={:?}",
            node.position()
        ),
        Node::MdxJsxTextElement(_) => bail!(
            "unsupported markdown node: MdxJsxTextElement position={:?}",
            node.position()
        ),
        Node::Link(link) => {
            write!(
                content,
                r#"<a href="{}">"#,
                text_sanitize_for_html(&link.url, false)
            )?;
            for child in &link.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            write!(content, r#"</a>"#)?;
        }
        Node::LinkReference(_) => bail!(
            "unsupported markdown node: LinkReference position={:?}",
            node.position()
        ),
        Node::Strong(strong) => {
            write!(content, "<strong>")?;
            for child in &strong.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            write!(content, "</strong>")?;
        }
        Node::Text(text) => {
            let sanitized = text_sanitize_for_html(&text.value, false);
            write!(content, "{}", sanitized)?;
        }
        Node::Code(code) => {
            let sanitized = text_sanitize_for_html(&code.value, false);
            let lang = code.lang.as_ref().unwrap(); // Safe due to `md_lint_rec` checking that.
            write!(
                content,
                r#"<pre>
  <div class="code-header">
    <span>{}</span>
    <button class="copy-code" type="button"><svg aria-hidden="true" focusable="false" class="octicon octicon-copy" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" display="inline-block" overflow="visible" style="vertical-align: text-bottom;"><path d="M0 6.75C0 5.784.784 5 1.75 5h1.5a.75.75 0 0 1 0 1.5h-1.5a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-1.5a.75.75 0 0 1 1.5 0v1.5A1.75 1.75 0 0 1 9.25 16h-7.5A1.75 1.75 0 0 1 0 14.25Z"></path><path d="M5 1.75C5 .784 5.784 0 6.75 0h7.5C15.216 0 16 .784 16 1.75v7.5A1.75 1.75 0 0 1 14.25 11h-7.5A1.75 1.75 0 0 1 5 9.25Zm1.75-.25a.25.25 0 0 0-.25.25v7.5c0 .138.112.25.25.25h7.5a.25.25 0 0 0 .25-.25v-7.5a.25.25 0 0 0-.25-.25Z"></path></svg></button>
  </div>
  <code class="language-{}">"#,
                capitalize_first(lang),
                lang,
            )?;

            for line in sanitized.lines() {
                writeln!(
                    content,
                    r#"<span class="line-number"></span><span class="code-hl">{}</span>"#,
                    line
                )?;
            }
            writeln!(content, "</code></pre>")?;
        }
        Node::Math(_) => bail!(
            "unsupported markdown node: Math position={:?}",
            node.position()
        ),
        Node::MdxFlowExpression(_) => bail!(
            "unsupported markdown node: MdxFlowExpression position={:?}",
            node.position()
        ),
        Node::Heading(heading) => {
            let position = heading
                .position
                .as_ref()
                .ok_or(anyhow!("heading has no position"))?;
            let title = titles
                .iter()
                .find(|t| t.start_md_offset == position.start.offset)
                .ok_or_else(|| anyhow!("failed to find title: position={:?}", position))?;

            writeln!(content, r#"<h{} id="{}">"#, heading.depth, title.slug)?;
            write!(content, r##"  <a class="title" href="#{}">"##, title.slug)?;
            for child in &heading.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            writeln!(content, "</a>")?;
            writeln!(
                content,
                r##"  <a class="hash-anchor" href="#{}" aria-hidden="true" onclick="navigator.clipboard.writeText(this.href);"></a>"##,
                title.slug
            )?;
            writeln!(content, "</h{}>", heading.depth)?;
        }
        Node::Table(table) => {
            writeln!(content, "<table>")?;
            let (thead, tbdody) = table.children.split_first().ok_or(anyhow!("expected table element to have thead and tbody as first two children, but it did not"))?;
            writeln!(content, "<thead>")?;
            md_to_html_rec(content, footnote_defs, thead, titles, true)?;
            writeln!(content, "</thead>")?;

            writeln!(content, "<tbody>")?;
            for child in tbdody {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            writeln!(content, "</tbody>")?;

            writeln!(content, "</table>\n\n")?;
        }
        Node::ThematicBreak(_) => {
            writeln!(content, "<hr />")?;
        }
        Node::TableRow(table_row) => {
            writeln!(content, "<tr>")?;
            for child in &table_row.children {
                md_to_html_rec(content, footnote_defs, child, titles, inside_thead)?;
            }
            writeln!(content, "</tr>")?;
        }
        Node::TableCell(table_cell) => {
            let tag = if inside_thead { "th" } else { "td" };
            write!(content, "<{}>", tag)?;
            for child in &table_cell.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            writeln!(content, "</{}>", tag)?;
        }
        Node::ListItem(list_item) => {
            write!(content, "<li>")?;
            let children = if list_item.children.len() == 1
                && let Node::Paragraph(p) = &list_item.children[0]
            {
                &p.children
            } else {
                &list_item.children
            };
            for child in children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            writeln!(content, "</li>")?;
        }
        Node::Definition(_) => bail!(
            "unsupported markdown node: Definition position={:?}",
            node.position()
        ),
        Node::Paragraph(paragraph) => {
            write!(content, "<p>")?;
            for child in &paragraph.children {
                md_to_html_rec(content, footnote_defs, child, titles, false)?;
            }
            writeln!(content, "</p>")?;
        }
    }
    Ok(())
}

fn text_sanitize_for_html(s: &str, sanitize_single_quote: bool) -> Cow<'_, str> {
    if !s.contains(['&', '<', '>', '"', '\'']) {
        Cow::Borrowed(s)
    } else {
        let mut result = String::with_capacity(s.len());
        for c in s.chars() {
            match c {
                '&' => result.push_str("&amp;"),
                '<' => result.push_str("&lt;"),
                '>' => result.push_str("&gt;"),
                '"' => result.push_str("&quot;"),
                '\'' => {
                    if sanitize_single_quote {
                        result.push_str("&#39;")
                    } else {
                        result.push('\'');
                    }
                }
                other => result.push(other),
            }
        }
        Cow::Owned(result)
    }
}

fn md_render_toc(content: &mut Vec<u8>, titles: &[Title]) -> anyhow::Result<()> {
    if titles.is_empty() {
        return Ok(());
    }

    writeln!(
        content,
        r#"  <details class="toc"><summary>Table of contents</summary>
<ul>"#
    )?;

    // Heading depths of the `<ul>` levels currently open. The one written just
    // above is the base level and is never closed inside the loop.
    let base_depth = titles[0].depth;
    let mut open_depths: Vec<u8> = vec![base_depth];

    for (i, title) in titles.iter().enumerate() {
        // `md_lint` rejects an article whose headings start below `##` or skip
        // a level, so the stack below just follows them. It still opens one
        // level at a time and pops instead of subtracting depths, so even
        // unlinted input cannot make it underflow or misnest.
        let depth = title.depth;
        let current_depth = open_depths.last().copied().unwrap_or(base_depth);

        if depth > current_depth {
            writeln!(content, "<ul>")?;
            open_depths.push(depth);
        } else {
            if i > 0 {
                // Close the previous item.
                writeln!(content, "</li>")?;
            }
            while open_depths.len() > 1 && depth < open_depths.last().copied().unwrap_or(base_depth)
            {
                open_depths.pop();
                writeln!(content, "</ul>\n</li>")?;
            }
        }

        writeln!(
            content,
            r##"
  <li>
    <a href="#{}">{}</a>"##,
            title.slug,
            text_sanitize_for_html(&title.text, false),
        )?;
    }

    // Final cleanup: close all remaining open tags. `titles` is not empty, so
    // there is always a last <li> to close.
    writeln!(content, "</li>")?;
    while open_depths.len() > 1 {
        open_depths.pop();
        writeln!(content, "</ul>\n</li>")?;
    }
    writeln!(content, "</ul>")?;
    writeln!(content, "</details>\n")?;

    Ok(())
}

fn md_render_article(
    git_stat: GitStat,
    html_header: &[u8],
    html_footer: &[u8],
    cache: &mut HashMap<u64, Article>,
) -> anyhow::Result<(u64, Article)> {
    let start = Instant::now();
    assert!(!html_header.is_empty());
    assert!(!html_footer.is_empty());

    let md_content_bytes = fs::read(&git_stat.path_from_git_root)
        .with_context(|| format!("failed to read file: {}", &git_stat.path_from_git_root))?;
    let hash = hash_article_inputs(&git_stat, html_header, html_footer, &md_content_bytes);

    if let Some(article) = cache.get(&hash) {
        return Ok((hash, article.clone()));
    }
    let md_content_bytes_len = md_content_bytes.len();
    let md_content = String::from_utf8(md_content_bytes).with_context(|| {
        format!(
            "failed to validate utf8: path={}",
            &git_stat.path_from_git_root
        )
    })?;

    let (md_root_title, tags) = md_parse_metadata(&md_content)?;

    let md_content_article = md_strip_metadata(&md_content).ok_or_else(|| {
        anyhow!(
            "no metadata delimiter found: path={}",
            &git_stat.path_from_git_root
        )
    })?;

    let md_path = PathBuf::from(&git_stat.path_from_git_root);
    let html_path = md_path.with_extension("html");
    let md_ast = match markdown::to_mdast(
        md_content_article,
        &ParseOptions {
            constructs: markdown::Constructs {
                gfm_autolink_literal: false,
                ..markdown::Constructs::gfm()
            },
            gfm_strikethrough_single_tilde: true,
            ..Default::default()
        },
    ) {
        Ok(x) => x,
        Err(err) => bail!(
            "failed to parse markdown: path={} err={:?}",
            &git_stat.path_from_git_root,
            err
        ),
    };

    md_lint(&md_ast, &md_path)?;

    let mut sb: Vec<u8> = Vec::with_capacity(md_content_bytes_len * 8);
    let html_root_title = String::from_utf8(md_to_html(md_root_title)?).with_context(|| {
        format!(
            "failed to validate utf8 for root title: path={}",
            &git_stat.path_from_git_root
        )
    })?;
    let text_root_title = md_to_text(md_root_title)?;

    writeln!(
        sb,
        "{}
<!DOCTYPE html>\n<html>\n<head>\n<title>{}</title>",
        AUTOGENERATED_COMMENT,
        text_sanitize_for_html(&text_root_title, false),
    )?;
    sb.extend(html_header);
    writeln!(sb, r#"{}<div class="article-prelude">"#, "\n")?;

    let (creation_date, _time) = git_stat.creation_date.split_once("T").with_context(|| {
        format!(
            "failed to parse creation date: path={} date={}",
            &git_stat.path_from_git_root, &git_stat.creation_date,
        )
    })?;

    let (modification_date, _time) =
        git_stat
            .modification_date
            .split_once("T")
            .with_context(|| {
                format!(
                    "failed to parse modification date: path={} date={}",
                    &git_stat.path_from_git_root, &git_stat.modification_date,
                )
            })?;
    writeln!(
        sb,
        r#"{}

<p class="publication-date">Published on {}. Last modified on {}.</p>"#,
        BACK_LINK, creation_date, modification_date,
    )?;
    writeln!(sb, r#"</div>"#)?;
    writeln!(
        sb,
        r#"<div class="article-title">
  <h1>{}</h1>"#,
        &html_root_title,
    )?;

    write!(sb, r#"<div class="tags"> "#)?;
    for tag in &tags {
        let id = html_slug(tag);
        write!(
            sb,
            r#"<a href="/blog/articles-by-tag.html#{}" class="tag">{}</a> "#,
            id,
            text_sanitize_for_html(tag, false)
        )?;
    }
    writeln!(sb, r#"</div>"#)?;
    writeln!(sb, r#"</div>"#)?;

    let mut md_titles = Vec::with_capacity(12);
    let mut title_to_counter: BTreeMap<String, u32> = BTreeMap::new();
    md_collect_titles(&md_ast, &mut title_to_counter, &mut md_titles)?;

    md_render_toc(&mut sb, &md_titles)?;

    let mut footnote_defs = Vec::with_capacity(8);
    md_to_html_rec(&mut sb, &mut footnote_defs, &md_ast, &md_titles, false)?;
    md_render_footnote_definitions(&mut sb, &footnote_defs)?;

    writeln!(sb, "{}", BACK_LINK)?;
    sb.extend(html_footer);

    let article = Article {
        git_stat,
        html_title: html_root_title,
        text_title: text_root_title,

        html_path,
        tags: tags.iter().map(|t| t.to_string()).collect(),
        html_output: sb,
    };

    cache.insert(hash, article.clone());

    println!(
        "⏳ cache miss: generated {} in {} us",
        &article.git_stat.path_from_git_root,
        Instant::now().duration_since(start).as_micros()
    );

    Ok((hash, article))
}

fn md_render_footnote_definitions(
    content: &mut Vec<u8>,
    footnote_defs: &[FootnoteDefinition],
) -> anyhow::Result<()> {
    if footnote_defs.is_empty() {
        return Ok(());
    }

    writeln!(
        content,
        r#"<section class="footnotes" data-footnotes>
<ol>"#
    )?;

    for def in footnote_defs {
        writeln!(content, r#"<li id="fn-{}">"#, def.identifier)?;

        let [child] = def.children.as_slice() else {
            bail!(
                "expected exactly one paragraph in footnote definition: id={} children={}",
                def.identifier,
                def.children.len()
            );
        };
        let children = match child {
            Node::Paragraph(p) => &p.children,
            other => bail!(
                "expected a paragraph in footnote definition: id={} position={:?}",
                def.identifier,
                other.position()
            ),
        };

        writeln!(content, r#"<p>"#)?;
        for child in children {
            md_to_html_rec(content, &mut vec![], child, &[], false)?;
        }

        writeln!(
            content,
            r##"<a href="#fnref-{}" class="footnote-backref" data-footnote-backref data-footnote-backref-idx="{}" aria-label="Back to reference {}">↩</a>"##,
            &def.identifier, &def.identifier, &def.identifier
        )?;

        writeln!(
            content,
            r#"</p>
</li>"#
        )?;
    }
    writeln!(
        content,
        r#"</ol>
</section>"#
    )?;
    Ok(())
}

fn generate_tags_page(
    articles: &[Article],
    html_header: &[u8],
    html_footer: &[u8],
) -> anyhow::Result<()> {
    let start = Instant::now();

    let sb = tags_page_build(articles, html_header, html_footer)?;
    fs::write("articles-by-tag.html", sb).context("failed to write articles-by-tag.html")?;

    println!(
        "⚙️ generated articles-by-tag.html: {} us",
        Instant::now().duration_since(start).as_micros()
    );
    Ok(())
}

fn tags_page_build(
    articles: &[Article],
    html_header: &[u8],
    html_footer: &[u8],
) -> anyhow::Result<Vec<u8>> {
    let mut tag_to_articles = BTreeMap::new();

    for article in articles {
        for tag in &article.tags {
            tag_to_articles
                .entry(tag.clone())
                .or_insert_with(Vec::new)
                .push(article);
        }
    }

    for tag1 in tag_to_articles.keys() {
        for tag2 in tag_to_articles.keys() {
            if tag1 != tag2 && tag1.to_lowercase() == tag2.to_lowercase() {
                bail!(
                    "similar tags detected with different case: {} vs {}",
                    tag1,
                    tag2
                );
            }
        }
    }

    let mut sb: Vec<u8> = Vec::with_capacity(64000);
    writeln!(
        sb,
        "<!DOCTYPE html>\n<html>\n<head>\n<title>Articles by tag</title>",
    )?;
    sb.extend(html_header);
    sb.extend(BACK_LINK.as_bytes());

    writeln!(sb, "\n<h1>Articles by tag</h1>\n<ul>",)?;

    for (tag, articles) in &mut tag_to_articles {
        articles.sort_by(|a, b| a.git_stat.creation_date.cmp(&b.git_stat.creation_date));

        writeln!(
            sb,
            "<li id=\"{}\"><span class=\"tag\">{}</span><ul>",
            html_slug(tag),
            text_sanitize_for_html(tag, false)
        )?;

        for a in articles {
            sb.extend(b"<li>\n");
            let (date, _time) = a
                .git_stat
                .creation_date
                .split_once("T")
                .ok_or(anyhow!("failed to parse date"))?;
            writeln!(sb, "  <span class=\"date\">{}</span>", date)?;
            writeln!(
                sb,
                "  <a href=\"{}\">{}</a>\n</li>",
                &a.html_path.to_string_lossy(),
                &a.html_title
            )?;
        }
        writeln!(sb, "</ul></li>",)?;
    }
    writeln!(sb, "</ul>",)?;

    sb.extend(html_footer);

    Ok(sb)
}

fn generate_article_rss(
    sb: &mut Vec<u8>,
    base_uuid: &uuid::Uuid,
    article: &Article,
) -> anyhow::Result<()> {
    let article_uuid =
        uuid::Uuid::new_v5(base_uuid, article.html_path.to_string_lossy().as_bytes());
    write!(
        sb,
        r#"
<entry>
<title>{}</title>
<link href="{}/{}"/>
<id>urn:uuid:{}</id>
<updated>{}</updated>
<published>{}</published>
</entry>
    "#,
        text_sanitize_for_html(&article.text_title, true),
        BASE_URL,
        article
            .html_path
            .to_str()
            .ok_or(anyhow!("failed to convert path to str"))?,
        &article_uuid,
        article.git_stat.modification_date,
        article.git_stat.creation_date,
    )?;

    Ok(())
}

fn generate_rss(articles: &mut [Article]) -> anyhow::Result<()> {
    let start = Instant::now();

    let sb = rss_build(articles)?;
    fs::write("feed.xml", sb).context("failed to write feed.xml")?;

    println!(
        "⚙️ generated feed.xml: {} us",
        Instant::now().duration_since(start).as_micros()
    );

    Ok(())
}

fn rss_build(articles: &mut [Article]) -> anyhow::Result<Vec<u8>> {
    articles.sort_by(|a, b| {
        a.git_stat
            .creation_date
            .as_str()
            .cmp(&b.git_stat.creation_date)
    });

    let mut sb = Vec::with_capacity(32000);
    let blog_uuid = uuid::Builder::from_bytes(FEED_UUID).into_uuid();

    // `articles` is sorted by creation date, and the most recently created
    // article is not necessarily the most recently modified one.
    let last_modification_date = articles
        .iter()
        .map(|a| a.git_stat.modification_date.as_str())
        .max()
        .ok_or(anyhow!("no article to build the feed from"))?;

    writeln!(
        sb,
        r#"<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
<title>Philippe Gaultier's blog</title>
<link href="{}"/>
<updated>{}</updated>
<author>
  <name>Philippe Gaultier</name>
</author>
<id>urn:uuid:{}</id>
"#,
        BASE_URL, last_modification_date, blog_uuid,
    )?;

    for a in articles {
        generate_article_rss(&mut sb, &blog_uuid, a)?;
    }

    sb.extend(b"</feed>");

    Ok(sb)
}

fn generate_home_page(
    articles: &mut [Article],
    html_header: &[u8],
    html_footer: &[u8],
) -> anyhow::Result<()> {
    let start = Instant::now();

    articles.sort_by(|a, b| {
        b.git_stat
            .creation_date
            .as_str()
            .cmp(&a.git_stat.creation_date)
    });

    let mut sb = Vec::with_capacity(64 * 1024);

    sb.extend(b"<!DOCTYPE html>\n<html>\n<head>\n<title>");
    sb.extend(b"Philippe Gaultier's blog");
    sb.extend(b"</title>\n");
    sb.extend(html_header);
    sb.extend(b"\n<div class=\"articles\">\n");
    sb.extend(b"  <h2 id=\"articles\">Articles</h2>\n");
    sb.extend(b"  <ul>\n");

    for a in articles {
        if a.git_stat.path_from_git_root == "body_of_work.md" {
            continue;
        }

        sb.extend(b"\n  <li>\n    <div class=\"home-link\">\n");
        sb.extend(b"      <span class=\"date\">");
        // Assuming a helper for date formatting
        let (date, _time) = a
            .git_stat
            .creation_date
            .split_once("T")
            .ok_or(anyhow!("failed to parse data"))?;
        sb.extend(date.as_bytes());
        sb.extend(b"</span>\n");

        writeln!(
            sb,
            "      <a href=\"/blog/{}\">{}</a>",
            &a.html_path.to_string_lossy(),
            &a.html_title
        )?;

        sb.extend(b"    </div>\n<div class=\"tags\">\n");

        for tag in &a.tags {
            let slug = html_slug(tag);
            write!(
                sb,
                " <a href=\"/blog/articles-by-tag.html#{}\" class=\"tag\">{}</a>",
                slug,
                text_sanitize_for_html(tag, false)
            )?;
        }
        sb.extend(b"</div></li>");
    }

    sb.extend(b"  </ul>\n</div>\n");

    let markdown_content = fs::read_to_string("index.md").context("failed to read index.md")?;
    md_html_append(&markdown_content, &mut sb)?;

    sb.extend(html_footer);
    fs::write("index.html", sb).context("failed to write index.html")?;

    println!(
        "⚙️ generated index.html: {} us",
        Instant::now().duration_since(start).as_micros()
    );

    Ok(())
}

fn generate_all(cache: &mut HashMap<u64, Article>) -> anyhow::Result<()> {
    let start = std::time::Instant::now();
    let html_header = fs::read("header.html").context("failed to read header.html")?;
    let html_footer = fs::read("footer.html").context("failed to read footer.html")?;

    let git_stats = git_get_articles_stats()?;

    let mut articles: Vec<Article> = Vec::with_capacity(git_stats.len());
    let mut live_hashes: HashSet<u64> = HashSet::with_capacity(git_stats.len());
    let mut failures = 0usize;
    for gs in git_stats {
        if is_ignored_markdown_file(Path::new(&gs.path_from_git_root)) {
            continue;
        }

        match md_render_article(gs, &html_header, &html_footer, cache) {
            Ok((hash, a)) => {
                live_hashes.insert(hash);
                articles.push(a);
            }
            Err(err) => {
                // Keep going so that one broken article does not hide the rest,
                // but remember it: see the end of this function.
                eprintln!("err: failed to render article: err={:?}", err);
                failures += 1;
            }
        }
    }
    // Forget the articles that no longer exist in this shape. Without this the
    // cache keeps every past revision of every article alive for as long as
    // `watch` runs.
    cache.retain(|hash, _| live_hashes.contains(hash));

    for a in &articles {
        fs::write(&a.html_path, &a.html_output)
            .with_context(|| format!("failed to write {:?}", &a.html_path))?;
    }

    generate_home_page(&mut articles, &html_header, &html_footer)?;
    generate_tags_page(&articles, &html_header, &html_footer)?;
    generate_rss(&mut articles)?;
    let articles_count = articles.len();

    println!(
        "⚙️ generated {} articles in {} ms",
        articles_count,
        Instant::now().duration_since(start).as_millis()
    );

    if failures > 0 {
        bail!("{} article(s) failed to render", failures);
    }

    Ok(())
}

fn check_langs() {
    for lang in ["cmake", "scheme", "x86asm", "dockerfile"] {
        let exists = fs::exists(format!("{}.min.js", lang)).unwrap_or_default();
        assert!(exists, "{}", lang);
    }
}

// A panic while holding the lock poisons it. The data it guards is a counter
// that is still perfectly valid, and refusing to serve live-reload for the rest
// of the session because one rebuild panicked helps nobody.
fn lock_ignore_poison<T>(lock: &Mutex<T>) -> std::sync::MutexGuard<'_, T> {
    lock.lock().unwrap_or_else(|err| err.into_inner())
}

// Many editors save by writing a temporary file and renaming it over the
// target, which never produces `Modify(Data(..))`: on macOS FSEvents it shows
// up as `Create` or `Modify(Name(..))`. Only listening for data modifications
// missed those saves entirely.
fn watch_event_is_interesting(kind: &EventKind) -> bool {
    matches!(
        kind,
        EventKind::Create(_)
            | EventKind::Modify(ModifyKind::Any | ModifyKind::Data(_) | ModifyKind::Name(_))
    )
}

fn watch(mtx_cond: Arc<(Mutex<u64>, Condvar)>, cache: &mut HashMap<u64, Article>) {
    let (etx, erx) = std::sync::mpsc::channel::<notify::Result<notify::Event>>();
    let mut watcher = notify::recommended_watcher(etx).unwrap();
    watcher
        .watch(Path::new("."), RecursiveMode::NonRecursive)
        .unwrap();
    for res in erx {
        let event = match res {
            Ok(event) => event,
            Err(e) => {
                println!("watch error: {:?}", e);
                continue;
            }
        };

        if !watch_event_is_interesting(&event.kind) {
            continue;
        }

        let (lock, cvar) = &*mtx_cond;
        let mut generation = lock_ignore_poison(lock);
        for path in event.paths {
            // A watched path always has a final component, but do not bet the
            // watcher thread on it.
            let Some(file_name) = path.file_name() else {
                continue;
            };
            let file_name_str = file_name.to_string_lossy();

            if file_name == AsRef::<Path>::as_ref("header.html")
                || file_name == AsRef::<Path>::as_ref("footer.html")
            {
                println!("🔄 header/footer changed: {}", file_name_str);
                if let Err(err) = generate_all(cache) {
                    eprintln!("err: {:?}", err);
                }
                *generation += 1;
                cvar.notify_all();
            }
            if path.extension() == Some("js".as_ref())
                || path.extension() == Some("css".as_ref())
                || path.extension() == Some("svg".as_ref())
                || path.extension() == Some("png".as_ref())
                || path.extension() == Some("webm".as_ref())
                || path.extension() == Some("mp4".as_ref())
                || path.extension() == Some("jpeg".as_ref())
                || path.extension() == Some("ico".as_ref())
                || path.extension() == Some("gif".as_ref())
            {
                println!("🔄 asset changed: {}", file_name_str);

                *generation += 1;
                cvar.notify_all();
            }

            if path.extension() == Some("md".as_ref()) && !is_ignored_markdown_file(&path) {
                println!("🔄 md file changed: {}", file_name_str);
                if let Err(err) = generate_all(cache) {
                    eprintln!("err: {:?}", err);
                }

                *generation += 1;
                cvar.notify_all();
            }
        }
    }

    println!("end of file watch ");
}

// Minimal percent-decoding: a browser encodes spaces and non-ASCII bytes in
// asset names, and the file on disk is not called `my%20file.png`.
fn percent_decode(s: &str) -> Option<String> {
    if !s.contains('%') {
        return Some(s.to_owned());
    }

    let bytes = s.as_bytes();
    let mut res = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' {
            res.push(u8::from_str_radix(s.get(i + 1..i + 3)?, 16).ok()?);
            i += 3;
        } else {
            res.push(bytes[i]);
            i += 1;
        }
    }

    String::from_utf8(res).ok()
}

// Resolve a URL path to a file inside `root`, or `None` if it points outside of
// it. Everything but plain file/directory names is refused rather than
// resolved: there is nothing above the blog root worth serving.
fn http_resolve_path(root: &Path, url_path: &str) -> Option<PathBuf> {
    // A query string or a fragment is not part of the path.
    let url_path = url_path
        .split_once(['?', '#'])
        .map_or(url_path, |(path, _)| path);
    let rel = url_path.strip_prefix("/blog/")?;
    // Decode before validating the components, so that an escaped `..` is
    // caught by the loop below rather than sneaking through it.
    let rel = percent_decode(rel)?;

    let mut res = root.to_path_buf();
    for comp in Path::new(&rel).components() {
        match comp {
            std::path::Component::Normal(c) => res.push(c),
            _ => return None,
        }
    }

    // Symlinks can still point outside of the root, so check the real path too.
    let res = res.canonicalize().ok()?;
    if !res.starts_with(root) {
        return None;
    }

    Some(res)
}

fn get_content_type(path: &Path) -> &'static str {
    // A file name is not required to be UTF-8; fall back rather than panic.
    let extension = match path.extension().and_then(|e| e.to_str()) {
        None => return "text/plain",
        Some(e) => e,
    };

    match extension {
        "js" => "application/javascript",
        "gif" => "image/gif",
        "jpg" => "image/jpeg",
        "jpeg" => "image/jpeg",
        "ico" => "image/vnd.microsoft.icon",
        "png" => "image/png",
        "pdf" => "application/pdf",
        "htm" => "text/html; charset=utf8",
        "html" => "text/html; charset=utf8",
        "txt" => "text/plain; charset=utf8",
        "svg" => "image/svg+xml",
        "css" => "text/css; charset=utf-8",
        "mp4" => "video/mp4",
        _ => "text/plain; charset=utf8",
    }
}

#[derive(Debug, PartialEq, Eq)]
enum HttpReadError {
    // The client sent more than `HTTP_REQUEST_SIZE_MAX` without completing a
    // request.
    TooBig,
    // The connection closed before the request was complete.
    Eof,
    Io,
    Malformed,
}

impl std::fmt::Display for HttpReadError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            HttpReadError::TooBig => "request too big",
            HttpReadError::Eof => "connection closed mid-request",
            HttpReadError::Io => "read failed",
            HttpReadError::Malformed => "malformed request",
        };
        f.write_str(s)
    }
}

// Read until `req_bytes` holds one complete HTTP request. Every failure here is
// something a client can cause at will, so none of them may panic.
fn http_read_request<R: Read>(reader: R, req_bytes: &mut Vec<u8>) -> Result<(), HttpReadError> {
    // The equivalent of Go's `io.LimitReader`: hands out at most this many
    // bytes and then reports EOF, which bounds the request exactly instead of
    // to whatever the buffer capacity happened to grow to.
    let mut reader = reader.take(HTTP_REQUEST_SIZE_MAX as u64);

    loop {
        // Grow when full: a request bigger than the initial capacity used to
        // end up handing `read()` an empty slice, which reads 0 and drops the
        // connection without ever answering. `take` is what bounds this, so
        // the capacity itself needs no limit.
        if req_bytes.len() == req_bytes.capacity() {
            req_bytes.reserve(req_bytes.capacity().max(4096));
        }
        let cap = req_bytes.capacity();

        let old_len = req_bytes.len();
        // Zero the spare capacity so that `read()` gets a real `&mut [u8]`.
        // This does not reallocate since `len <= capacity`.
        req_bytes.resize(cap, 0);
        let read_count = match reader.read(&mut req_bytes[old_len..]) {
            Ok(read_count) => read_count,
            Err(_) => {
                req_bytes.truncate(old_len);
                return Err(HttpReadError::Io);
            }
        };
        req_bytes.truncate(old_len + read_count);
        if read_count == 0 {
            // `take` signals the limit as a plain EOF, so tell the two apart:
            // a client that hung up is not a client that flooded us.
            return Err(if reader.limit() == 0 {
                HttpReadError::TooBig
            } else {
                HttpReadError::Eof
            });
        }

        let mut headers = [httparse::EMPTY_HEADER; 1024];
        let mut req = httparse::Request::new(&mut headers);
        match req.parse(req_bytes) {
            Ok(parsed) if !parsed.is_partial() => return Ok(()),
            Ok(_) => {}
            Err(_) => return Err(HttpReadError::Malformed),
        }
    }
}

fn http_serve<F>(handler: F) -> io::Result<()>
where
    F: Fn(httparse::Request<'_, '_>, TcpStream) + Send + Sync + Clone + 'static,
{
    let addr: SocketAddr = "127.0.0.1:8001".parse().unwrap();

    let listener = TcpListener::bind(addr)?;
    println!("Open: http://{}/blog", addr);

    loop {
        let (mut stream, _) = listener.accept()?;

        let handler = handler.clone();
        thread::spawn(move || {
            // Do not let a stalled client hold a thread forever.
            if let Err(err) = stream.set_read_timeout(Some(HTTP_READ_TIMEOUT)) {
                eprintln!("http: failed to set the read timeout: {}", err);
                return;
            }

            let mut req_bytes: Vec<u8> = Vec::with_capacity(10 * 1024); // 10 KiB.
            if let Err(err) = http_read_request(&mut stream, &mut req_bytes) {
                eprintln!("http: dropping request: {}", err);
                return;
            }

            let mut headers = [httparse::EMPTY_HEADER; 1024];
            let mut req = httparse::Request::new(&mut headers);
            // It parsed once already inside `http_read_request`.
            if req.parse(&req_bytes).is_err() {
                return;
            }
            handler(req, stream);
        });
    }
}

// Block until the build generation moves past `seen`, and return the new value.
//
// Waiting on the generation rather than on a bare notification is what makes
// this reliable: a rebuild finishing between two waits used to be lost, and a
// spurious wakeup used to send a reload event that nothing had asked for.
fn wait_for_next_generation(mtx_cond: &(Mutex<u64>, Condvar), seen: u64) -> u64 {
    let (lock, cvar) = mtx_cond;
    let guard = lock_ignore_poison(lock);
    let guard = cvar
        .wait_while(guard, |generation| *generation == seen)
        .unwrap_or_else(|err| err.into_inner());

    *guard
}

fn live_reload(
    mut resp: BufWriter<TcpStream>,
    mtx_cond: Arc<(Mutex<u64>, Condvar)>,
) -> Result<(), ()> {
    write!(
        resp,
        "HTTP/1.1 200\r\nCache-Control: no-cache\r\nContent-Type: text/event-stream\r\n\r\n"
    )
    .map_err(|_| ())?;
    // The headers sit in the `BufWriter` until something flushes it, and the
    // browser will not consider the stream open before it sees them.
    resp.flush().map_err(|_| ())?;

    let mut seen = *lock_ignore_poison(&mtx_cond.0);

    loop {
        seen = wait_for_next_generation(&mtx_cond, seen);

        write!(resp, "data: foobar\n\n").map_err(|_| ())?;
        resp.flush().map_err(|_| ())?;
        println!("🔃 sse event sent");
    }
}

fn main() -> ExitCode {
    let mut args = std::env::args().skip(1);
    let arg1 = args.next();

    check_langs();

    let mut cache = HashMap::with_capacity(128);

    let mut exit_code = ExitCode::SUCCESS;
    if let Err(err) = generate_all(&mut cache) {
        eprintln!("err: {:?}", err);
        exit_code = ExitCode::FAILURE;
    }

    if let Some(arg) = arg1
        && arg == "watch"
    {
        let serve_root = std::env::current_dir()
            .and_then(|d| d.canonicalize())
            .expect("failed to resolve the current directory");

        let mtx_cond = Arc::new((Mutex::new(0u64), Condvar::new()));

        let mtx_cond2 = Arc::clone(&mtx_cond);

        thread::spawn(move || {
            watch(mtx_cond2, &mut cache);
        });

        if let Err(err) = http_serve(move |req, stream| {
            let mut resp = BufWriter::new(stream);
            match (req.method.unwrap(), req.path.unwrap()) {
                ("GET", "/blog") => {
                    // The client can vanish at any point: never panic on a write.
                    let _ = write!(
                        resp,
                        "HTTP/1.1 301\r\nLocation: /blog/index.html\r\nConnection: Close\r\n\r\n"
                    );
                }
                ("GET", "/blog/live-reload") => {
                    let _ = live_reload(resp, mtx_cond.clone());
                }
                _ => {
                    let url_path = req.path.unwrap();
                    let path = match http_resolve_path(&serve_root, url_path) {
                        Some(path) => path,
                        None => {
                            eprintln!("refused path: url_path={}", url_path);
                            let _ = write!(resp, "HTTP/1.1 404\r\nConnection: Close\r\n\r\n");
                            return;
                        }
                    };

                    let content = match std::fs::read(&path) {
                        Ok(content) => content,
                        Err(err) => {
                            eprintln!(
                                "file not found: url_path={} path={:?} err={}",
                                url_path, &path, err
                            );
                            let _ = write!(resp, "HTTP/1.1 404\r\nConnection: Close\r\n\r\n");
                            return;
                        }
                    };

                    let _ = write!(
                        resp,
                        "HTTP/1.1 200\r\nContent-Length: {}\r\nContent-Type: {}\r\n\r\n",
                        content.len(),
                        get_content_type(&path)
                    );
                    let _ = resp.write_all(&content);
                }
            };
        }) {
            eprintln!("err: http server: {}", err);
            return ExitCode::FAILURE;
        }
    }

    exit_code
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    // ---------------------------------------------------------------- helpers

    fn parse_md(md: &str) -> Node {
        markdown::to_mdast(
            md,
            &ParseOptions {
                constructs: markdown::Constructs {
                    gfm_autolink_literal: false,
                    ..markdown::Constructs::gfm()
                },
                gfm_strikethrough_single_tilde: true,
                ..Default::default()
            },
        )
        .unwrap()
    }

    fn render_md(md: &str) -> anyhow::Result<String> {
        let mut out = Vec::new();
        md_html_append(md, &mut out)?;
        Ok(String::from_utf8(out).unwrap())
    }

    fn lint_md(md: &str) -> anyhow::Result<()> {
        md_lint(&parse_md(md), Path::new("test.md"))
    }

    fn collect_titles(md: &str) -> Vec<Title> {
        let mut titles = Vec::new();
        let mut counters = BTreeMap::new();
        md_collect_titles(&parse_md(md), &mut counters, &mut titles).unwrap();
        titles
    }

    fn test_title(text: &str, depth: u8, start_md_offset: usize) -> Title {
        Title {
            text: text.to_owned(),
            depth,
            start_md_offset,
            slug: html_slug(text),
        }
    }

    fn render_toc(titles: &[Title]) -> String {
        let mut out = Vec::new();
        md_render_toc(&mut out, titles).unwrap();
        String::from_utf8(out).unwrap()
    }

    // Build an article the way `md_render_article` does, so the tests exercise
    // the real title conversions.
    fn test_article(html_path: &str, title_md: &str, created: &str, modified: &str) -> Article {
        Article {
            git_stat: GitStat {
                creation_date: created.to_owned(),
                modification_date: modified.to_owned(),
                path_from_git_root: html_path.replace(".html", ".md"),
            },
            html_title: String::from_utf8(md_to_html(title_md).unwrap()).unwrap(),
            text_title: md_to_text(title_md).unwrap(),
            html_path: PathBuf::from(html_path),
            tags: Vec::new(),
            html_output: Vec::new(),
        }
    }

    // Check that every `<ul>`/`<li>` is closed, in the right order.
    fn assert_tags_balanced(html: &str) {
        let mut stack: Vec<&str> = Vec::new();
        let mut rest = html;
        while let Some(pos) = rest.find('<') {
            rest = &rest[pos..];
            if rest.starts_with("<ul>") {
                stack.push("ul");
            } else if rest.starts_with("<li>") {
                stack.push("li");
            } else if rest.starts_with("</ul>") {
                assert_eq!(Some("ul"), stack.pop(), "misnested </ul> in:\n{}", html);
            } else if rest.starts_with("</li>") {
                assert_eq!(Some("li"), stack.pop(), "misnested </li> in:\n{}", html);
            }
            rest = &rest[1..];
        }
        assert!(stack.is_empty(), "unclosed {:?} in:\n{}", stack, html);
    }

    fn repo_root() -> PathBuf {
        // Tests run with the crate root as the working directory.
        std::env::current_dir().unwrap().canonicalize().unwrap()
    }

    // ------------------------------------------------------- 1. path traversal

    #[test]
    fn point_1_serving_is_confined_to_the_blog_root() {
        let root = repo_root();

        // Real files under the root resolve.
        assert_eq!(
            Some(root.join("Cargo.toml")),
            http_resolve_path(&root, "/blog/Cargo.toml")
        );
        assert_eq!(
            Some(root.join("src").join("main.rs")),
            http_resolve_path(&root, "/blog/src/main.rs")
        );

        // Traversal is refused rather than resolved.
        assert_eq!(None, http_resolve_path(&root, "/blog/../Cargo.toml"));
        assert_eq!(
            None,
            http_resolve_path(&root, "/blog/../../../../etc/passwd")
        );
        assert_eq!(None, http_resolve_path(&root, "/blog/./../Cargo.toml"));

        // An absolute path with no `/blog/` prefix is not a blog path at all;
        // it used to be handed straight to `fs::read`.
        assert_eq!(None, http_resolve_path(&root, "/etc/passwd"));
        assert_eq!(None, http_resolve_path(&root, "/etc/blog/passwd"));
    }

    // ------------------------------------------- 2. malformed requests

    #[test]
    fn point_2_a_malformed_request_is_an_error_not_a_panic() {
        let mut req_bytes = Vec::with_capacity(1024);
        let mut reader = Cursor::new(b"this is not http\r\n\r\n".to_vec());
        assert_eq!(
            Err(HttpReadError::Malformed),
            http_read_request(&mut reader, &mut req_bytes)
        );

        // A client hanging up mid-request is an error, not a panic either.
        let mut req_bytes = Vec::with_capacity(1024);
        let mut reader = Cursor::new(b"GET /blog/index.html HTTP/1.1\r\n".to_vec());
        assert_eq!(
            Err(HttpReadError::Eof),
            http_read_request(&mut reader, &mut req_bytes)
        );

        // And a well-formed request still goes through.
        let mut req_bytes = Vec::with_capacity(1024);
        let mut reader = Cursor::new(b"GET /blog/index.html HTTP/1.1\r\nHost: x\r\n\r\n".to_vec());
        assert_eq!(Ok(()), http_read_request(&mut reader, &mut req_bytes));
    }

    // ------------------------------------- 3. reading into a real buffer

    // Hands out one byte at a time, so the request spans many `read` calls.
    struct DripReader {
        data: Vec<u8>,
        pos: usize,
    }

    impl Read for DripReader {
        fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
            if self.pos >= self.data.len() || buf.is_empty() {
                return Ok(0);
            }
            buf[0] = self.data[self.pos];
            self.pos += 1;
            Ok(1)
        }
    }

    #[test]
    fn point_3_a_request_split_across_reads_is_reassembled_exactly() {
        let req = b"GET /blog/index.html HTTP/1.1\r\nHost: x\r\nAccept: */*\r\n\r\n";
        let mut reader = DripReader {
            data: req.to_vec(),
            pos: 0,
        };
        let mut req_bytes = Vec::with_capacity(1024);

        assert_eq!(Ok(()), http_read_request(&mut reader, &mut req_bytes));
        // Byte-for-byte: no uninitialized slack, no stray padding.
        assert_eq!(req.as_slice(), req_bytes.as_slice());
    }

    // -------------------------------------------- 4. request buffer growth

    #[test]
    fn point_4_a_request_larger_than_the_initial_buffer_still_parses() {
        let mut req = String::from("GET /blog/index.html HTTP/1.1\r\n");
        for i in 0..400 {
            req.push_str(&format!("X-Padding-{}: {}\r\n", i, "y".repeat(64)));
        }
        req.push_str("\r\n");
        assert!(req.len() > 10 * 1024, "the test request must exceed 10 KiB");

        let mut reader = Cursor::new(req.clone().into_bytes());
        let mut req_bytes = Vec::with_capacity(10 * 1024);

        assert_eq!(Ok(()), http_read_request(&mut reader, &mut req_bytes));
        assert_eq!(req.len(), req_bytes.len());
    }

    #[test]
    fn point_4_an_endless_request_is_cut_off() {
        struct Endless;
        impl Read for Endless {
            fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
                buf.fill(b'x');
                Ok(buf.len())
            }
        }

        let mut req_bytes = Vec::with_capacity(10 * 1024);
        assert_eq!(
            Err(HttpReadError::TooBig),
            http_read_request(&mut Endless, &mut req_bytes)
        );
        // Exactly the limit, not "however far the capacity had doubled".
        assert_eq!(HTTP_REQUEST_SIZE_MAX, req_bytes.len());
    }

    // ------------------------------------------------ 5 & 6. feed titles

    #[test]
    fn points_5_and_6_feed_titles_are_plain_text_escaped_once() {
        let mut articles = vec![
            test_article(
                "quotes.html",
                r#"Perhaps Rust needs "defer""#,
                "2024-01-01T00:00:00+00:00",
                "2024-01-02T00:00:00+00:00",
            ),
            test_article(
                "code.html",
                "In Rust, `let _ = ...` is special",
                "2024-01-03T00:00:00+00:00",
                "2024-01-04T00:00:00+00:00",
            ),
        ];
        let xml = String::from_utf8(rss_build(&mut articles).unwrap()).unwrap();

        // Escaped exactly once. `&amp;quot;` was the double-escaped output.
        assert!(
            xml.contains("<title>Perhaps Rust needs &quot;defer&quot;</title>"),
            "{}",
            xml
        );
        assert!(!xml.contains("&amp;quot;"), "{}", xml);

        // An Atom title is `type="text"`, so no markup may reach it.
        assert!(
            xml.contains("<title>In Rust, let _ = ... is special</title>"),
            "{}",
            xml
        );
        assert!(!xml.contains("&lt;code&gt;"), "{}", xml);
    }

    // ------------------------------------------------ 7. table of contents

    #[test]
    fn point_7_toc_escapes_heading_text() {
        let html = render_toc(&[test_title("Light & Dark mode", 2, 0)]);
        assert!(html.contains("Light &amp; Dark mode"), "{}", html);
        assert!(!html.contains("Light & Dark mode"), "{}", html);
    }

    // ------------------------------------------------- 8. document title

    #[test]
    fn point_8_the_document_title_is_escaped_plain_text() {
        // Exactly what `md_render_article` writes into `<head><title>`.
        let title_of =
            |md: &str| text_sanitize_for_html(&md_to_text(md).unwrap(), false).into_owned();

        // Markdown syntax does not belong in a browser tab.
        assert_eq!(
            "In Rust, let _ = ... is special",
            title_of("In Rust, `let _ = ...` is special")
        );
        // Nor does an unescaped `&`.
        assert_eq!("Tom &amp; Jerry", title_of("Tom & Jerry"));
    }

    #[test]
    fn point_8_strikethrough_survives_flattening_to_text() {
        // Dropping the tildes leaves a title that reads as nonsense.
        assert_eq!(
            "Making my blog ~11~ 33 times faster",
            md_to_text("Making my blog ~11~ 33 times faster").unwrap()
        );
    }

    // ------------------------------------------------ 9. toc nesting

    #[test]
    fn heading_lint_rejects_a_top_level_heading() {
        // The `<h1>` is rendered from the `Title:` metadata, so the body may
        // not introduce another one.
        assert!(lint_md("# Not allowed\n").is_err());
        assert!(lint_md("## Allowed\n").is_ok());
    }

    #[test]
    fn heading_lint_requires_headings_to_nest_one_level_at_a_time() {
        // Skipping a level down.
        assert!(lint_md("## Two\n\n#### Four\n").is_err());
        // The first heading is one level below the metadata title, so it must
        // be `##` and not deeper.
        assert!(lint_md("### Three first\n").is_err());

        // Descending one at a time is fine.
        assert!(lint_md("## Two\n\n### Three\n\n#### Four\n").is_ok());
        // And coming back up may skip as many levels as it likes.
        assert!(lint_md("## Two\n\n### Three\n\n#### Four\n\n## Two again\n").is_ok());
    }

    #[test]
    fn point_9_toc_survives_headings_that_do_not_nest() {
        // `md_lint` rejects all of these before the renderer sees them; this
        // pins that the renderer cannot panic or misnest if one slips through.
        // `##` first and `#` after: this underflowed `current - base`.

        assert_tags_balanced(&render_toc(&[
            test_title("Deep first", 2, 0),
            test_title("Shallow after", 1, 10),
        ]));

        // A skipped level must not open a `<ul>` outside of any `<li>`.
        let html = render_toc(&[test_title("Two", 2, 0), test_title("Four", 4, 10)]);
        assert_tags_balanced(&html);
        assert!(!html.contains("<ul>\n<ul>"), "{}", html);

        // Descending several levels at once, then back up.
        assert_tags_balanced(&render_toc(&[
            test_title("A", 2, 0),
            test_title("B", 5, 1),
            test_title("C", 2, 2),
        ]));

        // And the ordinary shape still nests.
        let html = render_toc(&[
            test_title("A", 2, 0),
            test_title("B", 3, 1),
            test_title("C", 3, 2),
            test_title("D", 2, 3),
        ]);
        assert_tags_balanced(&html);
        assert!(html.contains("<ul>"), "{}", html);
    }

    #[test]
    fn point_9_an_empty_toc_renders_nothing() {
        assert_eq!("", render_toc(&[]));
    }

    // ------------------------------------------------- 10. cache key

    #[test]
    fn point_10_the_cache_key_covers_the_article_identity() {
        let a = GitStat {
            creation_date: "2024-01-01T00:00:00+00:00".to_owned(),
            modification_date: "2024-01-02T00:00:00+00:00".to_owned(),
            path_from_git_root: "a.md".to_owned(),
        };
        let mut different_path = a.clone();
        different_path.path_from_git_root = "b.md".to_owned();
        let mut different_date = a.clone();
        different_date.creation_date = "2023-01-01T00:00:00+00:00".to_owned();

        let (header, footer, body) = (b"header".as_slice(), b"footer".as_slice(), b"same body");

        let key = hash_article_inputs(&a, header, footer, body);
        assert_eq!(
            key,
            hash_article_inputs(&a, header, footer, body),
            "the key must be stable"
        );
        assert_ne!(
            key,
            hash_article_inputs(&different_path, header, footer, body),
            "two articles with the same body are not interchangeable"
        );
        assert_ne!(
            key,
            hash_article_inputs(&different_date, header, footer, body),
            "the rendered page embeds the dates"
        );
    }

    // ------------------------------------------------ 11. feed <updated>

    #[test]
    fn point_11_the_feed_updated_is_the_latest_modification() {
        let mut articles = vec![
            // Published first, but edited most recently.
            test_article(
                "old.html",
                "Old",
                "2024-01-01T00:00:00+00:00",
                "2026-06-01T00:00:00+00:00",
            ),
            // Published last, edited long ago: `.last()` used to pick this one.
            test_article(
                "new.html",
                "New",
                "2025-01-01T00:00:00+00:00",
                "2025-01-02T00:00:00+00:00",
            ),
        ];
        let xml = String::from_utf8(rss_build(&mut articles).unwrap()).unwrap();

        let feed_updated = xml
            .lines()
            .find(|line| line.starts_with("<updated>"))
            .unwrap();
        assert_eq!("<updated>2026-06-01T00:00:00+00:00</updated>", feed_updated);
    }

    // ------------------------------------------------ 12. git log parsing

    #[test]
    fn point_12_a_rename_keeps_the_original_creation_date() {
        let log = concat!(
            "'2019-09-04T08:41:29+02:00'\n",
            "\n",
            "A\tadvent_of_code_5.md\n",
            "'2019-09-05T11:45:48+02:00'\n",
            "\n",
            "R100\tadvent_of_code_5.md\tadvent_of_code_2018_5.md\n",
        );

        let stats = git_parse_log(log).unwrap();
        assert_eq!(1, stats.len());
        assert_eq!("advent_of_code_2018_5.md", stats[0].path_from_git_root);
        assert_eq!("2019-09-04T08:41:29+02:00", stats[0].creation_date);
        assert_eq!("2019-09-05T11:45:48+02:00", stats[0].modification_date);
    }

    #[test]
    fn point_12_add_modify_and_delete_are_tracked() {
        let log = concat!(
            "'2024-01-01T00:00:00+00:00'\n",
            "\n",
            "A\tkept.md\n",
            "A\tgone.md\n",
            "'2024-02-01T00:00:00+00:00'\n",
            "\n",
            "M\tkept.md\n",
            "D\tgone.md\n",
        );

        let stats = git_parse_log(log).unwrap();
        assert_eq!(1, stats.len());
        assert_eq!("kept.md", stats[0].path_from_git_root);
        assert_eq!("2024-01-01T00:00:00+00:00", stats[0].creation_date);
        assert_eq!("2024-02-01T00:00:00+00:00", stats[0].modification_date);
    }

    // -------------------------------------- 13. renderer errors, not panics

    #[test]
    fn point_13_a_heading_with_inline_markup_renders() {
        // This used to trip `assert_eq!(1, heading.children.len())`.
        let html = render_md("# Using `foo` here\n").unwrap();
        assert!(html.contains("<code>foo</code>"), "{}", html);
    }

    #[test]
    fn point_13_unsupported_nodes_are_reported_not_panicked_on() {
        // `Node::Definition`, previously `todo!()`.
        assert!(render_md("[ref]: /blog/somewhere\n").is_err());
        // `Node::Break`, likewise.
        assert!(render_md("one  \ntwo\n").is_err());
    }

    // ---------------------------------------------- 15. metadata delimiter

    #[test]
    fn point_15_the_metadata_delimiter_is_a_line_of_its_own() {
        assert_eq!(
            Some("\nBody\n"),
            md_strip_metadata("Title: A\nTags: b\n---\n\nBody\n")
        );

        // A `---` inside the title used to become the split point and swallow
        // the beginning of the article.
        assert_eq!(
            Some("\nBody\n"),
            md_strip_metadata("Title: A --- B\nTags: c\n---\n\nBody\n")
        );

        // No delimiter at all is reported rather than guessed at.
        assert_eq!(None, md_strip_metadata("Title: A\nTags: b\n\nBody\n"));
    }

    // ------------------------------------------------- 16. watch events

    #[test]
    fn point_16_rename_and_create_events_count_as_changes() {
        use notify::event::{
            AccessKind, CreateKind, DataChange, MetadataKind, ModifyKind, RemoveKind, RenameMode,
        };

        // A save that goes through a temporary file and a rename.
        assert!(watch_event_is_interesting(&EventKind::Create(
            CreateKind::File
        )));
        assert!(watch_event_is_interesting(&EventKind::Modify(
            ModifyKind::Name(RenameMode::To)
        )));
        // A plain in-place write, which was the only kind handled before.
        assert!(watch_event_is_interesting(&EventKind::Modify(
            ModifyKind::Data(DataChange::Content)
        )));
        assert!(watch_event_is_interesting(&EventKind::Modify(
            ModifyKind::Any
        )));

        // Reading a file, or touching only its metadata, is not a change.
        assert!(!watch_event_is_interesting(&EventKind::Access(
            AccessKind::Read
        )));
        assert!(!watch_event_is_interesting(&EventKind::Modify(
            ModifyKind::Metadata(MetadataKind::Any)
        )));
        assert!(!watch_event_is_interesting(&EventKind::Remove(
            RemoveKind::File
        )));
    }

    // ------------------------------------------------- 17. live reload

    #[test]
    fn point_17_a_rebuild_before_the_wait_is_not_lost() {
        let mtx_cond = Arc::new((Mutex::new(0u64), Condvar::new()));

        // The rebuild lands before any client waits. A bare `cvar.wait` slept
        // straight through this and the browser kept the stale page.
        {
            let (lock, cvar) = &*mtx_cond;
            *lock_ignore_poison(lock) += 1;
            cvar.notify_all();
        }

        assert_eq!(1, wait_for_next_generation(&mtx_cond, 0));
    }

    #[test]
    fn point_17_a_rebuild_during_the_wait_wakes_the_client() {
        let mtx_cond = Arc::new((Mutex::new(7u64), Condvar::new()));

        let writer = Arc::clone(&mtx_cond);
        let handle = thread::spawn(move || {
            thread::sleep(Duration::from_millis(50));
            let (lock, cvar) = &*writer;
            *lock_ignore_poison(lock) += 1;
            cvar.notify_all();
        });

        assert_eq!(8, wait_for_next_generation(&mtx_cond, 7));
        handle.join().unwrap();
    }

    #[test]
    fn point_17_a_poisoned_lock_does_not_take_down_the_clients() {
        let mtx_cond = Arc::new((Mutex::new(0u64), Condvar::new()));

        let poisoner = Arc::clone(&mtx_cond);
        let _ = thread::spawn(move || {
            let _guard = poisoner.0.lock().unwrap();
            panic!("a rebuild blew up while holding the lock");
        })
        .join();
        assert!(mtx_cond.0.is_poisoned());

        // The counter is still perfectly valid, so clients keep working.
        {
            let (lock, cvar) = &*mtx_cond;
            *lock_ignore_poison(lock) += 1;
            cvar.notify_all();
        }
        assert_eq!(1, wait_for_next_generation(&mtx_cond, 0));
    }

    // ------------------------------------------------------ minor points

    #[test]
    fn minor_url_paths_are_decoded_and_query_strings_ignored() {
        assert_eq!(Some("a b.png".to_owned()), percent_decode("a%20b.png"));
        assert_eq!(Some("é".to_owned()), percent_decode("%C3%A9"));
        assert_eq!(Some("plain".to_owned()), percent_decode("plain"));
        assert_eq!(None, percent_decode("%zz"));
        assert_eq!(None, percent_decode("%2"));

        let root = repo_root();
        assert_eq!(
            Some(root.join("Cargo.toml")),
            http_resolve_path(&root, "/blog/Cargo.toml?v=2")
        );
        assert_eq!(
            Some(root.join("Cargo.toml")),
            http_resolve_path(&root, "/blog/Cargo.toml#section")
        );

        // An escaped traversal is decoded first, then refused by the component
        // check -- not passed through as a literal file name.
        assert_eq!(None, http_resolve_path(&root, "/blog/%2e%2e/Cargo.toml"));
    }

    #[test]
    fn minor_image_url_and_alt_are_escaped() {
        let html = render_md("![a \"quoted\" alt](/img/a&b.png)\n").unwrap();
        assert!(
            html.contains(r#"alt="a &quot;quoted&quot; alt""#),
            "{}",
            html
        );
        assert!(html.contains(r#"src="/img/a&amp;b.png""#), "{}", html);
    }

    #[test]
    fn minor_tag_names_are_escaped() {
        let mut article = test_article(
            "a.html",
            "A",
            "2024-01-01T00:00:00+00:00",
            "2024-01-01T00:00:00+00:00",
        );
        article.tags = vec!["C & C++".to_owned()];

        let html =
            String::from_utf8(tags_page_build(&[article], b"<header>", b"<footer>").unwrap())
                .unwrap();

        assert!(html.contains("C &amp; C++"), "{}", html);
        assert!(!html.contains(">C & C++<"), "{}", html);
    }

    #[test]
    fn minor_tags_differing_only_in_case_are_rejected() {
        let mut lower = test_article(
            "a.html",
            "A",
            "2024-01-01T00:00:00+00:00",
            "2024-01-01T00:00:00+00:00",
        );
        lower.tags = vec!["rust".to_owned()];
        let mut upper = test_article(
            "b.html",
            "B",
            "2024-01-02T00:00:00+00:00",
            "2024-01-02T00:00:00+00:00",
        );
        upper.tags = vec!["Rust".to_owned()];

        assert!(tags_page_build(&[lower, upper], b"<header>", b"<footer>").is_err());
    }

    #[test]
    fn minor_the_spelling_lint_matches_whole_words() {
        // The misspellings the lint exists for.
        assert!(lint_md("It uses dtrace here.").is_err());
        assert!(lint_md("A 100KB file.").is_err());
        assert!(lint_md("Only 4 kb left.").is_err());

        // Punctuation and digits bound a word just like whitespace does, so
        // these are caught even though `split_whitespace` would not see them.
        assert!(lint_md("A dtrace-based tool.").is_err());
        assert!(lint_md("Reads at 100KB/s.").is_err());
        assert!(lint_md("(dtrace)").is_err());

        // Not misspellings: `kb` inside a word, and the correct spellings.
        assert!(lint_md("At the workbench.").is_ok());
        assert!(lint_md("It uses DTrace, 4 kB and 8 KiB.").is_ok());
        assert!(lint_md("A 100 kB/s link and an 8 KiB buffer.").is_ok());
    }

    #[test]
    fn minor_anchors_are_deduplicated_on_the_slug() {
        // `Foo!` and `Foo?` are different titles that slug identically, so
        // counting per title text produced two `id="foo"`.
        let titles = collect_titles("# Foo!\n\n# Foo?\n\n# Foo!\n");
        let slugs: Vec<&str> = titles.iter().map(|t| t.slug.as_str()).collect();

        assert_eq!(vec!["foo", "foo-1", "foo-2"], slugs);
    }

    #[test]
    fn minor_malformed_git_log_is_an_error_not_a_panic() {
        // Missing the empty line that follows the date.
        assert!(git_parse_log("'2024-01-01T00:00:00+00:00'\nA\ta.md\n").is_err());
        // A modification to a path that was never added.
        assert!(git_parse_log("'2024-01-01T00:00:00+00:00'\n\nM\tghost.md\n").is_err());
        // An action the parser does not know.
        assert!(git_parse_log("'2024-01-01T00:00:00+00:00'\n\nZ\ta.md\n").is_err());
        // An empty log is not an error.
        assert!(git_parse_log("").unwrap().is_empty());
    }

    #[test]
    fn minor_ignored_markdown_files_match_on_the_file_name() {
        assert!(is_ignored_markdown_file(Path::new("README.md")));
        assert!(is_ignored_markdown_file(Path::new("./todo.md")));
        // The generator and the watcher used to disagree about this one.
        assert!(is_ignored_markdown_file(Path::new("posts/index.md")));

        assert!(!is_ignored_markdown_file(Path::new("an_article.md")));
        assert!(!is_ignored_markdown_file(Path::new("readme.md")));
    }

    #[test]
    fn minor_content_type_never_panics() {
        assert_eq!(
            "text/html; charset=utf8",
            get_content_type(Path::new("a.html"))
        );
        assert_eq!("image/png", get_content_type(Path::new("a.png")));
        assert_eq!("text/plain", get_content_type(Path::new("no_extension")));

        // A file name that is not valid UTF-8 used to hit `to_str().unwrap()`.
        #[cfg(unix)]
        {
            use std::os::unix::ffi::OsStrExt;
            let name = std::ffi::OsStr::from_bytes(b"a.\xff\xfe");
            assert_eq!("text/plain", get_content_type(Path::new(name)));
        }
    }
}
